// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv5Qw2uMIwmkFtku6dDNHwLaNlRYA33qs',
    appId: '1:812890776053:web:ed6f55b7e6b59192de00bc',
    messagingSenderId: '812890776053',
    projectId: 'unitravel-47678',
    authDomain: 'unitravel-47678.firebaseapp.com',
    storageBucket: 'unitravel-47678.appspot.com',
    measurementId: 'G-2P3Q55PTFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLwhNuGS7aSdjpEIhGd7QR6XwhAbswkr4',
    appId: '1:812890776053:android:14aabac49b8d52cade00bc',
    messagingSenderId: '812890776053',
    projectId: 'unitravel-47678',
    storageBucket: 'unitravel-47678.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU_-5HHg0N9vOHMksNcyslHMpquW9Bp_0',
    appId: '1:812890776053:ios:2eed19160fb436a9de00bc',
    messagingSenderId: '812890776053',
    projectId: 'unitravel-47678',
    storageBucket: 'unitravel-47678.appspot.com',
    iosBundleId: 'com.example.travel1Movil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU_-5HHg0N9vOHMksNcyslHMpquW9Bp_0',
    appId: '1:812890776053:ios:5663f69c81d8a832de00bc',
    messagingSenderId: '812890776053',
    projectId: 'unitravel-47678',
    storageBucket: 'unitravel-47678.appspot.com',
    iosBundleId: 'com.example.travel1Movil.RunnerTests',
  );
}
